# cymep configuration
# A tag to identify data and figures output by cymep using this configuration
filename_out: "rean_configs"

# Specify particular ocean basin or hemisphere
# Basins - NATL, ENP, CP, WNP, NI, MED, SI, AUS, SP, SA, SH
# Use "N" or "S" to specify hemisphere
# Leave empty for global
basin: "NATL"

# Length of side of each square gridbox used for spatial analysis in degrees
gridsize: 8.0

# Extra region around the gridbox used for spatial analysis if focused on a single basin
grid_buffer: 10.0

# Start and end year for overlapping interannual correlation analysis
styr: 1980
enyr: 2019

# Filter out years external to styr and enyr for all analysis?
# If False keep all data
truncate_years: False

# First and last month to include in climatology
# If enmon < stmon, it will overlap December/January (e.g. 11, 12, 1, 2)
stmon: 1
enmon: 12

# Threshold wind (in m/s) for ACE calculations.
# Leave empty for no threshold
THRESHOLD_ACE_WIND:

# Threshold pressure (in hPa) for PACE calculations.
# Leave empty for no threshold
THRESHOLD_PACE_PRES:

# Apply a wind-speed threshold of 17.5 to the reference set of tracks?
# (the first entry in datasets)
# False for no filter
do_special_filter_obs: True

# Fill missing data with observed pressure-wind curve?
# False leaves data as missing
do_fill_missing_pw: True

# Define maximum intensity location by minimum PSL?
# False uses maximum wind
do_defineMIbypres: False

# Dataset configurations
# The directory containing your tracks. Can be absolute or relative to where cymep is
# run
path_to_data: "trajs/"

# Units of SLP data on tracks
# cymep works with hPa, so specify "Pa" to divide by 100 when loaded or "hPa" for no
# change
slp_units: "Pa"

# Keywords passed to huracanpy.load() for all datasets
# Can also be specified for each dataset if they require additional keywords
load_keywords:
  tracker: tempestextremes
  tempest_extremes_unstructured: False
  variable_names:
    - slp
    - wind
    - unknown

# Specify the track data to apply the analysis to
# datasets is a dictionary mapping a name (used in the output files) for each dataset to
# a dictionary of options for each dataset
# - filename:       The file containing the set of tracks
# - load_keywords:  Any additional keywords that need to be passed to huracanpy.load()
#                   for this dataset
# - ensmembers:     Number of ensemble members included in the dataset
# - yearspermember: Number of years per ensemble member in the datasets
# - windcorrs:      Wind speed correction factor
datasets:
  OBS:
    filename: ibtracs-1980-2019-GLOB.v4.txt
    load_keywords: {}
    ensmembers: 1
    yearspermember: 40
    windcorrs: 1.0

  ERAI:
    filename: trajectories.txt.ERAI
    load_keywords: {}
    ensmembers: 1
    yearspermember: 39
    windcorrs: 1.0

  20CRv3:
    filename: trajectories.txt.CR20
    load_keywords: {}
    ensmembers: 1
    yearspermember: 36
    windcorrs: 1.0

  MERRA:
    filename: trajectories.txt.MERRA
    load_keywords: {}
    ensmembers: 1
    yearspermember: 36
    windcorrs: 0.85

  MERRA2:
    filename: trajectories.txt.MERRA2
    load_keywords: {}
    ensmembers: 1
    yearspermember: 39
    windcorrs: 0.85

  JRA:
    filename: trajectories.txt.JRA
    load_keywords: {}
    ensmembers: 1
    yearspermember: 39
    windcorrs: 0.98

  CFSR:
    filename: trajectories.txt.CFSR
    load_keywords: {}
    ensmembers: 1
    yearspermember: 39
    windcorrs: 0.883

  ERA5:
    filename: trajectories.txt.ERA5
    load_keywords: {}
    ensmembers: 1
    yearspermember: 39
    windcorrs: 1.0
